# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]
NDArray="NDArray" # numpy
NdArray="NdArray" # onnxruntime::session::NdArray

[default.extend-words]

[files]
extend-exclude = ["*.svg"]
